version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/python:3.12.1
      - image: cimg/postgres:12.17.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: eventing
          POSTGRES_HOST: 127.0.0.1


    working_directory: ~/eventing

    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . env/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports