# Generated by Django 5.0.1 on 2024-01-23 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='ebd_hour',
            new_name='end_hour',
        ),
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
