# Generated by Django 5.0.1 on 2024-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0002_rename_ebd_hour_events_end_hour_events_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_hour',
            field=models.TimeField(null=True),
        ),
    ]
